spring.application.name=iba-sistema
server.port=${PORT:8181}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.time-zone=America/Sao_Paulo

logging.level.com.iba=DEBUG
logging.level.org.hibernate.SQL=DEBUG